FROM node:alpine3.24 AS build

WORKDIR /home/node/app

COPY package*.json ./
RUN npm install
COPY --exclude=node_modules --exclude=dist . .
RUN npm run build

ENTRYPOINT ["sh", "./scripts/startup.sh"]
CMD ["prod"]