#STAGE 1
FROM node:alpine3.24 AS build

WORKDIR /home/node/app

COPY package*.json ./
RUN npm install
COPY --exclude=node_modules --exclude=dist . .
RUN npm run build

#STAGE 2
FROM node:alpine3.24

WORKDIR /home/node/app

COPY package*.json ./
RUN npm install --omit=dev
COPY --from=build /home/node/app/dist ./dist
COPY ./prisma ./prisma
COPY ./scripts ./scripts

# See: https://github.com/prisma/orm/issues/28983
COPY ./prisma7.config.ts ./prisma7.config.ts

ENTRYPOINT ["sh", "./scripts/startup.sh"]
CMD ["prod"]